- hosts : myserver
  vars:
    - image: umar1807/webapache
  tasks:
    - name: install pytho-docker di ubuntu
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-docker
      when: ansible_distribution == "Ubuntu"

    - name: install python-docker di centos
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-docker
      when: ansible_distribution == "CentOS"

    - name: pull image docker
      docker_image:
        name: "{{ image }}"
        state: present
        force: yes

    - name: run container
      docker_container:
        name: web_server
        image: "{{ image }}"
        state: started
        published_ports:
           - 10000:80
        recreate: yes
